# Generated by Django 4.2.15 on 2025-01-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SongSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo", models.IntegerField(blank=True)),
                ("danceability", models.IntegerField(blank=True)),
                ("energy", models.IntegerField(blank=True)),
                ("valence", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=50)),
                ("genre", models.CharField(blank=True, max_length=200)),
                ("audio_file", models.FileField(upload_to="")),
                (
                    "hashtags",
                    models.ManyToManyField(
                        blank=True, null=True, to="music_app.hashtag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField()),
                (
                    "hashtags",
                    models.ManyToManyField(
                        blank=True, null=True, to="music_app.hashtag"
                    ),
                ),
                ("songs", models.ManyToManyField(to="music_app.song")),
            ],
        ),
    ]
