# Generated by Django 4.2.15 on 2025-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="hashtags",
        ),
        migrations.RemoveField(
            model_name="song",
            name="hashtags",
        ),
        migrations.AddField(
            model_name="playlist",
            name="hashtags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="song",
            name="hashtags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
