# Generated by Django 4.2.15 on 2025-01-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0002_remove_playlist_hashtags_remove_song_hashtags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(upload_to="songs/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
