# Generated by Django 4.2.15 on 2025-01-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_desc", models.CharField(max_length=200)),
                ("preferred_genres", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
