# Generated by Django 4.2.15 on 2025-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="preferredGenres",
            new_name="preferred_genres",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
