# Generated by Django 4.2.15 on 2025-01-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_app",
            "0002_rename_preferredgenres_userprofile_preferred_genres_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_desc",
        ),
    ]
