# Generated by Django 4.2.15 on 2025-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinteraction",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="userinteraction",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="userinteraction",
            name="user",
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="artist_name",
            field=models.CharField(default="Unknown Artist", max_length=50),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="genre",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
