# Generated by Django 4.2.15 on 2025-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_remove_userinteraction_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="interaction_type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
